export interface LexiconEntry {
  strongs: string;
  lemma: string;
  hebrew?: string;
  greek?: string;
  transliteration: string;
  pronunciation: string;
  partOfSpeech: string;
  gloss: string;
  occurrences: number;
}

export const strongsHebrew: LexiconEntry[] = [
  { strongs: "H7225", lemma: "רֵאשִׁית", hebrew: "רֵאשִׁית", transliteration: "rēʾšîṯ", pronunciation: "ray-SHEET", partOfSpeech: "Noun", gloss: "beginning, chief, first, firstfruits", occurrences: 51 },
  { strongs: "H430", lemma: "אֱלֹהִים", hebrew: "אֱלֹהִים", transliteration: "ʾĕlōhîm", pronunciation: "el-o-HEEM", partOfSpeech: "Noun", gloss: "God, gods, judges, angels", occurrences: 2600 },
  { strongs: "H1254", lemma: "בָּרָא", hebrew: "בָּרָא", transliteration: "bārāʾ", pronunciation: "ba-RA", partOfSpeech: "Verb", gloss: "to create, shape, form", occurrences: 48 },
  { strongs: "H8064", lemma: "שָׁמַיִם", hebrew: "שָׁמַיִם", transliteration: "šāmayim", pronunciation: "sha-MY-im", partOfSpeech: "Noun", gloss: "heavens, sky, firmament", occurrences: 421 },
  { strongs: "H776", lemma: "אֶרֶץ", hebrew: "אֶרֶץ", transliteration: "ʾereṣ", pronunciation: "EH-retz", partOfSpeech: "Noun", gloss: "earth, land, ground, country", occurrences: 2504 },
  { strongs: "H1961", lemma: "הָיָה", hebrew: "הָיָה", transliteration: "hāyâ", pronunciation: "ha-YA", partOfSpeech: "Verb", gloss: "to be, become, come to pass, exist", occurrences: 3512 },
  { strongs: "H8414", lemma: "תֹּהוּ", hebrew: "תֹּהוּ", transliteration: "tōhû", pronunciation: "to-HU", partOfSpeech: "Noun", gloss: "formlessness, chaos, emptiness, waste", occurrences: 20 },
  { strongs: "H922", lemma: "בֹּהוּ", hebrew: "בֹּהוּ", transliteration: "bōhû", pronunciation: "bo-HU", partOfSpeech: "Noun", gloss: "emptiness, void, desolation", occurrences: 3 },
  { strongs: "H2822", lemma: "חֹשֶׁךְ", hebrew: "חֹשֶׁךְ", transliteration: "ḥōšek", pronunciation: "KHO-shek", partOfSpeech: "Noun", gloss: "darkness, obscurity, ignorance", occurrences: 80 },
  { strongs: "H6440", lemma: "פָּנִים", hebrew: "פָּנִים", transliteration: "pānîm", pronunciation: "pa-NEEM", partOfSpeech: "Noun", gloss: "face, presence, surface, before", occurrences: 2129 },
  { strongs: "H8415", lemma: "תְּהוֹם", hebrew: "תְּהוֹם", transliteration: "tĕhôm", pronunciation: "te-HOME", partOfSpeech: "Noun", gloss: "deep, depths, abyss, primeval ocean", occurrences: 36 },
  { strongs: "H7307", lemma: "רוּחַ", hebrew: "רוּחַ", transliteration: "rûaḥ", pronunciation: "ROO-akh", partOfSpeech: "Noun", gloss: "wind, breath, spirit, mind", occurrences: 378 },
  { strongs: "H7363", lemma: "רָחַף", hebrew: "רָחַף", transliteration: "rāḥap̄", pronunciation: "ra-KHAF", partOfSpeech: "Verb", gloss: "to hover, brood, move gently", occurrences: 3 },
  { strongs: "H559", lemma: "אָמַר", hebrew: "אָמַר", transliteration: "ʾāmar", pronunciation: "a-MAR", partOfSpeech: "Verb", gloss: "to say, speak, utter, tell", occurrences: 5299 },
  { strongs: "H216", lemma: "אוֹר", hebrew: "אוֹר", transliteration: "ʾôr", pronunciation: "ore", partOfSpeech: "Noun", gloss: "light, daylight, illumination", occurrences: 123 },
  { strongs: "H7200", lemma: "רָאָה", hebrew: "רָאָה", transliteration: "rāʾâ", pronunciation: "ra-AH", partOfSpeech: "Verb", gloss: "to see, perceive, understand, inspect", occurrences: 1312 },
  { strongs: "H2896", lemma: "טוֹב", hebrew: "טוֹב", transliteration: "ṭôb", pronunciation: "tov", partOfSpeech: "Adjective", gloss: "good, pleasant, beautiful, excellent", occurrences: 741 },
  { strongs: "H914", lemma: "בָּדַל", hebrew: "בָּדַל", transliteration: "bādal", pronunciation: "ba-DAL", partOfSpeech: "Verb", gloss: "to separate, divide, distinguish", occurrences: 41 },
  { strongs: "H7121", lemma: "קָרָא", hebrew: "קָרָא", transliteration: "qārāʾ", pronunciation: "ka-RA", partOfSpeech: "Verb", gloss: "to call, proclaim, summon, name", occurrences: 734 },
  { strongs: "H3117", lemma: "יוֹם", hebrew: "יוֹם", transliteration: "yôm", pronunciation: "yome", partOfSpeech: "Noun", gloss: "day, time, year, daylight", occurrences: 2308 },
  { strongs: "H3915", lemma: "לַיְלָה", hebrew: "לַיְלָה", transliteration: "laylâ", pronunciation: "LAI-lah", partOfSpeech: "Noun", gloss: "night, darkness, nighttime", occurrences: 234 },
  { strongs: "H6153", lemma: "עֶרֶב", hebrew: "עֶרֶב", transliteration: "ʿereḇ", pronunciation: "EH-rev", partOfSpeech: "Noun", gloss: "evening, night, sunset", occurrences: 130 },
  { strongs: "H1242", lemma: "בֹּקֶר", hebrew: "בֹּקֶר", transliteration: "bōqer", pronunciation: "BO-ker", partOfSpeech: "Noun", gloss: "morning, dawn, early morning", occurrences: 215 },
  { strongs: "H6213", lemma: "עָשָׂה", hebrew: "עָשָׂה", transliteration: "ʿāśâ", pronunciation: "a-SA", partOfSpeech: "Verb", gloss: "to make, do, accomplish, produce", occurrences: 2633 },
  { strongs: "H7549", lemma: "רָקִיעַ", hebrew: "רָקִיעַ", transliteration: "rāqîaʿ", pronunciation: "ra-KEE-ah", partOfSpeech: "Noun", gloss: "firmament, expanse, vault of heaven", occurrences: 17 },
  { strongs: "H4325", lemma: "מַיִם", hebrew: "מַיִם", transliteration: "mayim", pronunciation: "MY-im", partOfSpeech: "Noun", gloss: "water, waters, flood, rain", occurrences: 582 },
  { strongs: "H6960", lemma: "קָוָה", hebrew: "קָוָה", transliteration: "qāvâ", pronunciation: "ka-VA", partOfSpeech: "Verb", gloss: "to wait, gather, collect, bind together", occurrences: 48 },
  { strongs: "H4725", lemma: "מָקוֹם", hebrew: "מָקוֹם", transliteration: "māqôm", pronunciation: "ma-KOME", partOfSpeech: "Noun", gloss: "place, location, space, site", occurrences: 401 },
  { strongs: "H3001", lemma: "יָבֵשׁ", hebrew: "יָבֵשׁ", transliteration: "yāḇēš", pronunciation: "ya-VESH", partOfSpeech: "Verb", gloss: "to dry up, be dry, become dry land", occurrences: 43 },
  { strongs: "H1870", lemma: "דֶּרֶךְ", hebrew: "דֶּרֶךְ", transliteration: "dereḵ", pronunciation: "DEH-rekh", partOfSpeech: "Noun", gloss: "way, road, journey, path, manner", occurrences: 706 },
  { strongs: "H5973", lemma: "עִם", hebrew: "עִם", transliteration: "ʿim", pronunciation: "eem", partOfSpeech: "Preposition", gloss: "with, along with, together with", occurrences: 1030 },
  { strongs: "H3068", lemma: "יְהוָֹה", hebrew: "יְהוָֹה", transliteration: "YHWH", pronunciation: "ad-o-NAI", partOfSpeech: "Noun", gloss: "LORD, Yahweh, the proper name of God", occurrences: 6519 },
  { strongs: "H1288", lemma: "בָּרַךְ", hebrew: "בָּרַךְ", transliteration: "bāraḵ", pronunciation: "ba-RAKH", partOfSpeech: "Verb", gloss: "to bless, praise, kneel down", occurrences: 327 },
  { strongs: "H6509", lemma: "פָּרָה", hebrew: "פָּרָה", transliteration: "pārâ", pronunciation: "pa-RA", partOfSpeech: "Verb", gloss: "to be fruitful, bear fruit, increase", occurrences: 29 },
  { strongs: "H7235", lemma: "רָבָה", hebrew: "רָבָה", transliteration: "rāḇâ", pronunciation: "ra-VA", partOfSpeech: "Verb", gloss: "to be many, multiply, increase, become numerous", occurrences: 224 },
  { strongs: "H4390", lemma: "מָלֵא", hebrew: "מָלֵא", transliteration: "mālēʾ", pronunciation: "ma-LEH", partOfSpeech: "Verb", gloss: "to fill, be full, accomplish, consecrate", occurrences: 250 },
  { strongs: "H5775", lemma: "עוֹף", hebrew: "עוֹף", transliteration: "ʿôp̄", pronunciation: "ofe", partOfSpeech: "Noun", gloss: "bird, fowl, winged creature", occurrences: 71 },
  { strongs: "H2416", lemma: "חַי", hebrew: "חַי", transliteration: "ḥay", pronunciation: "khai", partOfSpeech: "Adjective", gloss: "living, alive, life, animal", occurrences: 501 },
  { strongs: "H5315", lemma: "נֶפֶשׁ", hebrew: "נֶפֶשׁ", transliteration: "nepeš", pronunciation: "NEH-fesh", partOfSpeech: "Noun", gloss: "soul, life, self, person, being", occurrences: 754 },
  { strongs: "H7430", lemma: "רָמַשׂ", hebrew: "רָמַשׂ", transliteration: "rāmaś", pronunciation: "ra-MAS", partOfSpeech: "Verb", gloss: "to creep, move about, swarm", occurrences: 17 },
  { strongs: "H6754", lemma: "צֶלֶם", hebrew: "צֶלֶם", transliteration: "ṣelem", pronunciation: "TSEH-lem", partOfSpeech: "Noun", gloss: "image, likeness, idol, shadow", occurrences: 17 },
  { strongs: "H1823", lemma: "דְּמוּת", hebrew: "דְּמוּת", transliteration: "dəmûṯ", pronunciation: "de-MOOT", partOfSpeech: "Noun", gloss: "likeness, similitude, shape, pattern", occurrences: 25 },
  { strongs: "H7287", lemma: "רָדָה", hebrew: "רָדָה", transliteration: "rādâ", pronunciation: "ra-DA", partOfSpeech: "Verb", gloss: "to rule, dominate, have dominion, subdue", occurrences: 27 },
  { strongs: "H1710", lemma: "דָּגָה", hebrew: "דָּגָה", transliteration: "dāḡâ", pronunciation: "da-GA", partOfSpeech: "Noun", gloss: "fish (collective)", occurrences: 18 },
  { strongs: "H8552", lemma: "תָּמַם", hebrew: "תָּמַם", transliteration: "tāmam", pronunciation: "ta-MAM", partOfSpeech: "Verb", gloss: "to be complete, finished, ended, perfect", occurrences: 64 },
  { strongs: "H7676", lemma: "שַׁבָּת", hebrew: "שַׁבָּת", transliteration: "šabbāṯ", pronunciation: "sha-BAHT", partOfSpeech: "Noun", gloss: "Sabbath, day of rest, seventh day", occurrences: 108 },
  { strongs: "H6944", lemma: "קָדַשׁ", hebrew: "קָדַשׁ", transliteration: "qādaš", pronunciation: "ka-DASH", partOfSpeech: "Verb", gloss: "to be holy, consecrate, sanctify, set apart", occurrences: 172 },
  { strongs: "H1277", lemma: "בָּרִיא", hebrew: "בָּרִיא", transliteration: "bārîʾ", pronunciation: "ba-REE", partOfSpeech: "Adjective", gloss: "fat, robust, fertile", occurrences: 15 },
  { strongs: "H802", lemma: "אִשָּׁה", hebrew: "אִשָּׁה", transliteration: "ʾiššâ", pronunciation: "ee-SHA", partOfSpeech: "Noun", gloss: "woman, wife, female, spouse", occurrences: 781 },
  { strongs: "H376", lemma: "אִישׁ", hebrew: "אִישׁ", transliteration: "ʾîš", pronunciation: "eesh", partOfSpeech: "Noun", gloss: "man, husband, person, individual", occurrences: 2183 },
  { strongs: "H3528", lemma: "כְּבָר", hebrew: "כְּבָר", transliteration: "kəḇār", pronunciation: "ke-VAR", partOfSpeech: "Adverb", gloss: "already, long ago, before now", occurrences: 13 },
  { strongs: "H441", lemma: "אַלּוּף", hebrew: "אַלּוּף", transliteration: "ʾallûp̄", pronunciation: "al-LOOF", partOfSpeech: "Noun", gloss: "chief, clan leader, friend", occurrences: 43 },
  { strongs: "H3760", lemma: "כַּרְמֶל", hebrew: "כַּרְמֶל", transliteration: "karmel", pronunciation: "kar-MEL", partOfSpeech: "Noun", gloss: "garden land, orchard, fruitful field", occurrences: 13 },
  { strongs: "H7233", lemma: "רְבָבָה", hebrew: "רְבָבָה", transliteration: "rəḇāḇâ", pronunciation: "re-va-VA", partOfSpeech: "Noun", gloss: "ten thousand, myriad, countless number", occurrences: 16 },
  { strongs: "H1280", lemma: "בְּרִית", hebrew: "בְּרִית", transliteration: "bərîṯ", pronunciation: "be-REET", partOfSpeech: "Noun", gloss: "covenant, treaty, alliance, agreement", occurrences: 284 },
  { strongs: "H2617", lemma: "חֵסֵד", hebrew: "חֵסֵד", transliteration: "ḥēseḏ", pronunciation: "KHEH-sed", partOfSpeech: "Noun", gloss: "loving-kindness, mercy, steadfast love, grace", occurrences: 248 },
  { strongs: "H571", lemma: "אֶמֶת", hebrew: "אֶמֶת", transliteration: "ʾemeṯ", pronunciation: "EH-met", partOfSpeech: "Noun", gloss: "truth, faithfulness, reliability, trustworthiness", occurrences: 127 },
  { strongs: "H6666", lemma: "צְדָקָה", hebrew: "צְדָקָה", transliteration: "ṣəḏāqâ", pronunciation: "tse-da-KA", partOfSpeech: "Noun", gloss: "righteousness, justice, rightful cause", occurrences: 157 },
  { strongs: "H4940", lemma: "מִשְׁפָּחָה", hebrew: "מִשְׁפָּחָה", transliteration: "mišpāḥâ", pronunciation: "mish-pa-KHA", partOfSpeech: "Noun", gloss: "family, clan, tribe, kindred", occurrences: 302 },
  { strongs: "H7626", lemma: "שֵׁבֶט", hebrew: "שֵׁבֶט", transliteration: "šēḇeṭ", pronunciation: "SHEH-vet", partOfSpeech: "Noun", gloss: "tribe, rod, staff, scepter", occurrences: 190 },
  { strongs: "H3478", lemma: "יִשְׂרָאֵל", hebrew: "יִשְׂרָאֵל", transliteration: "yiśrāʾēl", pronunciation: "yis-ra-EL", partOfSpeech: "Noun", gloss: "Israel, one who strives with God", occurrences: 2507 },
  { strongs: "H1004", lemma: "בַּיִת", hebrew: "בַּיִת", transliteration: "bayiṯ", pronunciation: "BAH-yith", partOfSpeech: "Noun", gloss: "house, household, temple, dwelling", occurrences: 2051 },
  { strongs: "H5892", lemma: "עִיר", hebrew: "עִיר", transliteration: "ʿîr", pronunciation: "eer", partOfSpeech: "Noun", gloss: "city, town, fortified place", occurrences: 1095 },
  { strongs: "H2022", lemma: "הַר", hebrew: "הַר", transliteration: "har", pronunciation: "har", partOfSpeech: "Noun", gloss: "mountain, hill, hill country", occurrences: 545 },
  { strongs: "H5158", lemma: "נַחַל", hebrew: "נַחַל", transliteration: "naḥal", pronunciation: "NAKH-al", partOfSpeech: "Noun", gloss: "torrent, valley, wadi, stream", occurrences: 132 },
  { strongs: "H4057", lemma: "מִדְבָּר", hebrew: "מִדְבָּר", transliteration: "miḏbār", pronunciation: "mid-BAR", partOfSpeech: "Noun", gloss: "wilderness, desert, wasteland, uninhabited land", occurrences: 270 },
  { strongs: "H5921", lemma: "עַל", hebrew: "עַל", transliteration: "ʿal", pronunciation: "al", partOfSpeech: "Preposition", gloss: "on, upon, above, over, concerning", occurrences: 5763 },
  { strongs: "H5971", lemma: "עַם", hebrew: "עַם", transliteration: "ʿam", pronunciation: "am", partOfSpeech: "Noun", gloss: "people, nation, community, kinsmen", occurrences: 1868 },
  { strongs: "H1471", lemma: "גּוֹי", hebrew: "גּוֹי", transliteration: "gôy", pronunciation: "goy", partOfSpeech: "Noun", gloss: "nation, people, Gentile, foreign nation", occurrences: 559 },
  { strongs: "H4428", lemma: "מֶלֶךְ", hebrew: "מֶלֶךְ", transliteration: "meleḵ", pronunciation: "MEH-lekh", partOfSpeech: "Noun", gloss: "king, ruler, monarch, sovereign", occurrences: 2530 },
  { strongs: "H3548", lemma: "כֹּהֵן", hebrew: "כֹּהֵן", transliteration: "kōhēn", pronunciation: "ko-HEN", partOfSpeech: "Noun", gloss: "priest, minister, chief ruler", occurrences: 753 },
  { strongs: "H5030", lemma: "נָבִיא", hebrew: "נָבִיא", transliteration: "nāḇîʾ", pronunciation: "na-VEE", partOfSpeech: "Noun", gloss: "prophet, seer, spokesperson", occurrences: 319 },
  { strongs: "H2451", lemma: "חָכְמָה", hebrew: "חָכְמָה", transliteration: "ḥokmâ", pronunciation: "khok-MA", partOfSpeech: "Noun", gloss: "wisdom, skill, insight, shrewdness", occurrences: 153 },
  { strongs: "H8394", lemma: "תָּבוּן", hebrew: "תָּבוּן", transliteration: "tāḇûn", pronunciation: "ta-VOON", partOfSpeech: "Noun", gloss: "understanding, insight, discernment", occurrences: 42 },
  { strongs: "H998", lemma: "בִּינָה", hebrew: "בִּינָה", transliteration: "bînâ", pronunciation: "bee-NA", partOfSpeech: "Noun", gloss: "understanding, discernment, prudence", occurrences: 37 },
  { strongs: "H1847", lemma: "דַּעַת", hebrew: "דַּעַת", transliteration: "daʿaṯ", pronunciation: "DAH-ath", partOfSpeech: "Noun", gloss: "knowledge, awareness, discernment", occurrences: 93 },
  { strongs: "H3820", lemma: "לֵב", hebrew: "לֵב", transliteration: "lēḇ", pronunciation: "lev", partOfSpeech: "Noun", gloss: "heart, inner self, mind, will, conscience", occurrences: 599 },
  { strongs: "H5314", lemma: "נָפַשׁ", hebrew: "נָפַשׁ", transliteration: "nāp̄aš", pronunciation: "na-FASH", partOfSpeech: "Verb", gloss: "to be refreshed, take breath, rest", occurrences: 7 },
  { strongs: "H7965", lemma: "שָׁלוֹם", hebrew: "שָׁלוֹם", transliteration: "šālôm", pronunciation: "sha-LOME", partOfSpeech: "Noun", gloss: "peace, completeness, welfare, health", occurrences: 237 },
  { strongs: "H2398", lemma: "חָטָא", hebrew: "חָטָא", transliteration: "ḥāṭāʾ", pronunciation: "kha-TA", partOfSpeech: "Verb", gloss: "to sin, miss the mark, offend, bear guilt", occurrences: 238 },
  { strongs: "H2403", lemma: "חַטָּאת", hebrew: "חַטָּאת", transliteration: "ḥaṭṭāʾt", pronunciation: "khat-TAHT", partOfSpeech: "Noun", gloss: "sin, sin offering, punishment for sin", occurrences: 297 },
  { strongs: "H3722", lemma: "כָּפַר", hebrew: "כָּפַר", transliteration: "kāp̄ar", pronunciation: "ka-FAR", partOfSpeech: "Verb", gloss: "to atone, cover, appease, make reconciliation", occurrences: 103 },
  { strongs: "H6299", lemma: "פָּדָה", hebrew: "פָּדָה", transliteration: "pādâ", pronunciation: "pa-DA", partOfSpeech: "Verb", gloss: "to redeem, ransom, deliver, rescue", occurrences: 59 },
  { strongs: "H3444", lemma: "יְשׁוּעָה", hebrew: "יְשׁוּעָה", transliteration: "yəšûʿâ", pronunciation: "ye-shoo-AH", partOfSpeech: "Noun", gloss: "salvation, deliverance, victory, welfare", occurrences: 78 },
  { strongs: "H8085", lemma: "שָׁמַע", hebrew: "שָׁמַע", transliteration: "šāmaʿ", pronunciation: "sha-MAH", partOfSpeech: "Verb", gloss: "to hear, listen, obey, understand", occurrences: 1157 },
  { strongs: "H157", lemma: "אָהַב", hebrew: "אָהַב", transliteration: "ʾāhaḇ", pronunciation: "a-HAV", partOfSpeech: "Verb", gloss: "to love, have affection, like, desire", occurrences: 218 },
  { strongs: "H2136", lemma: "זָכַר", hebrew: "זָכַר", transliteration: "zāḵar", pronunciation: "za-KHAR", partOfSpeech: "Verb", gloss: "to remember, recall, bring to mind", occurrences: 233 },
  { strongs: "H3372", lemma: "יָרֵא", hebrew: "יָרֵא", transliteration: "yārēʾ", pronunciation: "ya-REH", partOfSpeech: "Verb", gloss: "to fear, revere, be afraid, respect", occurrences: 332 },
  { strongs: "H7321", lemma: "רוּעַ", hebrew: "רוּעַ", transliteration: "rûaʿ", pronunciation: "ROO-ah", partOfSpeech: "Verb", gloss: "to shout, raise a shout, sound an alarm", occurrences: 47 },
  { strongs: "H1984", lemma: "הָלַל", hebrew: "הָלַל", transliteration: "hālal", pronunciation: "ha-LAL", partOfSpeech: "Verb", gloss: "to praise, boast, celebrate, shine", occurrences: 164 },
  { strongs: "H2167", lemma: "זָמַר", hebrew: "זָמַר", transliteration: "zāmar", pronunciation: "za-MAR", partOfSpeech: "Verb", gloss: "to sing praise, make music, celebrate", occurrences: 45 },
  { strongs: "H3034", lemma: "יָדָה", hebrew: "יָדָה", transliteration: "yādâ", pronunciation: "ya-DA", partOfSpeech: "Verb", gloss: "to give thanks, praise, confess, acknowledge", occurrences: 114 },
  { strongs: "H3559", lemma: "כּוּן", hebrew: "כּוּן", transliteration: "kûn", pronunciation: "koon", partOfSpeech: "Verb", gloss: "to establish, fix, prepare, make ready", occurrences: 239 },
  { strongs: "H3426", lemma: "יֵשׁ", hebrew: "יֵשׁ", transliteration: "yēš", pronunciation: "yaysh", partOfSpeech: "Particle", gloss: "there is, there are, existence, substance", occurrences: 720 },
  { strongs: "H369", lemma: "אַיִן", hebrew: "אַיִן", transliteration: "ʾayin", pronunciation: "AH-yin", partOfSpeech: "Particle", gloss: "nothing, not, none, non-existence", occurrences: 751 },
  { strongs: "H6828", lemma: "צָפוֹן", hebrew: "צָפוֹן", transliteration: "ṣāp̄ôn", pronunciation: "tsa-FONE", partOfSpeech: "Noun", gloss: "north, hidden, dark, mysterious", occurrences: 153 },
  { strongs: "H1864", lemma: "דָּרוֹם", hebrew: "דָּרוֹם", transliteration: "dārôm", pronunciation: "da-ROHM", partOfSpeech: "Noun", gloss: "south, southern quarter", occurrences: 17 },
  { strongs: "H4217", lemma: "מִזְרָח", hebrew: "מִזְרָח", transliteration: "mizrāḥ", pronunciation: "miz-RAKH", partOfSpeech: "Noun", gloss: "east, sunrise, eastern quarter", occurrences: 74 },
  { strongs: "H3220", lemma: "יָם", hebrew: "יָם", transliteration: "yām", pronunciation: "yahm", partOfSpeech: "Noun", gloss: "sea, ocean, seaward, west", occurrences: 396 },
  { strongs: "H6780", lemma: "צֶמַח", hebrew: "צֶמַח", transliteration: "ṣemaḥ", pronunciation: "TSEH-makh", partOfSpeech: "Noun", gloss: "branch, sprout, growth, descendant", occurrences: 13 },
  { strongs: "H6529", lemma: "פְּרִי", hebrew: "פְּרִי", transliteration: "pərî", pronunciation: "pe-REE", partOfSpeech: "Noun", gloss: "fruit, produce, result, offspring", occurrences: 114 },
  { strongs: "H2233", lemma: "זֶרַע", hebrew: "זֶרַע", transliteration: "zeraʿ", pronunciation: "ZEH-rah", partOfSpeech: "Noun", gloss: "seed, offspring, descendant, posterity, semen", occurrences: 229 },
  { strongs: "H6218", lemma: "עָשׂוֹר", hebrew: "עָשׂוֹר", transliteration: "ʿāśôr", pronunciation: "a-SORE", partOfSpeech: "Noun", gloss: "ten, decade, tenth part", occurrences: 15 },
  { strongs: "H2563", lemma: "חֹמֶר", hebrew: "חֹמֶר", transliteration: "ḥōmer", pronunciation: "KHO-mer", partOfSpeech: "Noun", gloss: "clay, mortar, cement, mud", occurrences: 35 },
  { strongs: "H1285", lemma: "בְּרִית", hebrew: "בְּרִית", transliteration: "bərîṯ", pronunciation: "be-REET", partOfSpeech: "Noun", gloss: "covenant, treaty, compact, agreement", occurrences: 284 },
  { strongs: "H5486", lemma: "סוּף", hebrew: "סוּף", transliteration: "sûp̄", pronunciation: "soof", partOfSpeech: "Verb", gloss: "to end, consume, destroy, be at an end", occurrences: 17 },
  { strongs: "H1100", lemma: "בְּלִי", hebrew: "בְּלִי", transliteration: "bəlî", pronunciation: "be-LEE", partOfSpeech: "Preposition", gloss: "without, not, failure, wearing out", occurrences: 25 },
  { strongs: "H7706", lemma: "שַׁדַּי", hebrew: "שַׁדַּי", transliteration: "šadday", pronunciation: "shad-DAI", partOfSpeech: "Noun", gloss: "Almighty, Shaddai, All-Sufficient One", occurrences: 48 },
  { strongs: "H935", lemma: "בּוֹא", hebrew: "בּוֹא", transliteration: "bôʾ", pronunciation: "bo", partOfSpeech: "Verb", gloss: "to come, go, enter, arrive, bring", occurrences: 2582 },
  { strongs: "H3318", lemma: "יָצָא", hebrew: "יָצָא", transliteration: "yāṣāʾ", pronunciation: "ya-TSA", partOfSpeech: "Verb", gloss: "to go out, come out, emerge, proceed, depart", occurrences: 1072 },
  { strongs: "H5927", lemma: "עָלָה", hebrew: "עָלָה", transliteration: "ʿālâ", pronunciation: "a-LA", partOfSpeech: "Verb", gloss: "to go up, ascend, climb, rise, offer", occurrences: 894 },
  { strongs: "H3381", lemma: "יָרַד", hebrew: "יָרַד", transliteration: "yāraḏ", pronunciation: "ya-RAD", partOfSpeech: "Verb", gloss: "to go down, descend, sink, decline", occurrences: 380 },
  { strongs: "H3427", lemma: "יָשַׁב", hebrew: "יָשַׁב", transliteration: "yāšaḇ", pronunciation: "ya-SHAV", partOfSpeech: "Verb", gloss: "to sit, dwell, remain, inhabit, settle", occurrences: 1088 },
  { strongs: "H1980", lemma: "הָלַךְ", hebrew: "הָלַךְ", transliteration: "hālaḵ", pronunciation: "ha-LAKH", partOfSpeech: "Verb", gloss: "to walk, go, live, follow, travel", occurrences: 1555 },
  { strongs: "H6965", lemma: "קוּם", hebrew: "קוּם", transliteration: "qûm", pronunciation: "koom", partOfSpeech: "Verb", gloss: "to arise, stand up, establish, confirm", occurrences: 628 },
  { strongs: "H5414", lemma: "נָתַן", hebrew: "נָתַן", transliteration: "nāṯan", pronunciation: "na-TAN", partOfSpeech: "Verb", gloss: "to give, grant, set, put, place, appoint", occurrences: 2015 },
  { strongs: "H3947", lemma: "לָקַח", hebrew: "לָקַח", transliteration: "lāqaḥ", pronunciation: "la-KAKH", partOfSpeech: "Verb", gloss: "to take, receive, accept, seize, acquire", occurrences: 967 },
  { strongs: "H7971", lemma: "שָׁלַח", hebrew: "שָׁלַח", transliteration: "šālaḥ", pronunciation: "sha-LAKH", partOfSpeech: "Verb", gloss: "to send, dispatch, stretch out, let go", occurrences: 848 },
  { strongs: "H7973", lemma: "שֶׁלַח", hebrew: "שֶׁלַח", transliteration: "šelaḥ", pronunciation: "SHEH-lakh", partOfSpeech: "Noun", gloss: "missile, weapon, javelin, dart, shoot", occurrences: 8 },
  { strongs: "H4672", lemma: "מָצָא", hebrew: "מָצָא", transliteration: "māṣāʾ", pronunciation: "ma-TSA", partOfSpeech: "Verb", gloss: "to find, happen upon, meet, discover, attain", occurrences: 457 },
  { strongs: "H6680", lemma: "צָוָה", hebrew: "צָוָה", transliteration: "ṣāvâ", pronunciation: "tsa-VA", partOfSpeech: "Verb", gloss: "to command, appoint, charge, order", occurrences: 496 },
  { strongs: "H8104", lemma: "שָׁמַר", hebrew: "שָׁמַר", transliteration: "šāmar", pronunciation: "sha-MAR", partOfSpeech: "Verb", gloss: "to keep, guard, observe, watch, protect, preserve", occurrences: 469 },
  { strongs: "H3615", lemma: "כָּלָה", hebrew: "כָּלָה", transliteration: "kālâ", pronunciation: "ka-LA", partOfSpeech: "Verb", gloss: "to complete, finish, cease, consume, destroy", occurrences: 207 },
  { strongs: "H5307", lemma: "נָפַל", hebrew: "נָפַל", transliteration: "nāp̄al", pronunciation: "na-FAL", partOfSpeech: "Verb", gloss: "to fall, lie, cast down, prostrate, fail", occurrences: 434 },
  { strongs: "H4191", lemma: "מוּת", hebrew: "מוּת", transliteration: "mûṯ", pronunciation: "mooth", partOfSpeech: "Verb", gloss: "to die, kill, perish, be dead, be slain", occurrences: 842 },
  { strongs: "H2421", lemma: "חָיָה", hebrew: "חָיָה", transliteration: "ḥāyâ", pronunciation: "kha-YA", partOfSpeech: "Verb", gloss: "to live, be alive, revive, remain alive, restore", occurrences: 285 },
  { strongs: "H398", lemma: "אָכַל", hebrew: "אָכַל", transliteration: "ʾāḵal", pronunciation: "a-KHAL", partOfSpeech: "Verb", gloss: "to eat, devour, consume, feed, enjoy", occurrences: 809 },
  { strongs: "H8354", lemma: "שָׁתָה", hebrew: "שָׁתָה", transliteration: "šāṯâ", pronunciation: "sha-TA", partOfSpeech: "Verb", gloss: "to drink, imbibe, quench thirst", occurrences: 218 },
  { strongs: "H7937", lemma: "שָׁכַר", hebrew: "שָׁכַר", transliteration: "šāḵar", pronunciation: "sha-KHAR", partOfSpeech: "Verb", gloss: "to be drunk, become intoxicated", occurrences: 22 },
  { strongs: "H8101", lemma: "שֶׁמֶן", hebrew: "שֶׁמֶן", transliteration: "šemen", pronunciation: "SHEH-men", partOfSpeech: "Noun", gloss: "oil, fat, olive oil, richness, abundance", occurrences: 194 },
];

export const strongsGreek: LexiconEntry[] = [
  { strongs: "G3056", lemma: "λόγος", greek: "λόγος", transliteration: "lógos", pronunciation: "LO-gos", partOfSpeech: "Noun", gloss: "word, statement, message, account, reason, divine expression", occurrences: 330 },
  { strongs: "G2316", lemma: "Θεός", greek: "Θεός", transliteration: "Theós", pronunciation: "theh-OS", partOfSpeech: "Noun", gloss: "God, deity, the supreme being", occurrences: 1314 },
  { strongs: "G2258", lemma: "ἦν", greek: "ἦν", transliteration: "ēn", pronunciation: "ane", partOfSpeech: "Verb", gloss: "was, were, existed (imperfect of eimi)", occurrences: 2417 },
  { strongs: "G746", lemma: "ἀρχή", greek: "ἀρχή", transliteration: "archḗ", pronunciation: "ar-KHAY", partOfSpeech: "Noun", gloss: "beginning, origin, first, principality, ruler", occurrences: 55 },
  { strongs: "G2532", lemma: "καί", greek: "καί", transliteration: "kaí", pronunciation: "kai", partOfSpeech: "Conjunction", gloss: "and, even, also, namely, indeed, but", occurrences: 9161 },
  { strongs: "G4314", lemma: "πρός", greek: "πρός", transliteration: "prós", pronunciation: "pros", partOfSpeech: "Preposition", gloss: "to, toward, with, before, against, for", occurrences: 700 },
  { strongs: "G3588", lemma: "ὁ", greek: "ὁ", transliteration: "ho", pronunciation: "ho", partOfSpeech: "Article", gloss: "the (definite article), this, that", occurrences: 19870 },
  { strongs: "G3778", lemma: "οὗτος", greek: "οὗτος", transliteration: "hoûtos", pronunciation: "HOO-tos", partOfSpeech: "Pronoun", gloss: "this, these, he, she, it, they", occurrences: 1387 },
  { strongs: "G1510", lemma: "εἰμί", greek: "εἰμί", transliteration: "eimí", pronunciation: "ee-MEE", partOfSpeech: "Verb", gloss: "to be, exist, happen, am, is, are", occurrences: 2467 },
  { strongs: "G4160", lemma: "ποιέω", greek: "ποιέω", transliteration: "poiéō", pronunciation: "poy-EH-oh", partOfSpeech: "Verb", gloss: "to make, do, create, produce, accomplish", occurrences: 568 },
  { strongs: "G2980", lemma: "λαλέω", greek: "λαλέω", transliteration: "laléō", pronunciation: "la-LEH-oh", partOfSpeech: "Verb", gloss: "to speak, talk, utter words, tell", occurrences: 296 },
  { strongs: "G3004", lemma: "λέγω", greek: "λέγω", transliteration: "légō", pronunciation: "LEH-go", partOfSpeech: "Verb", gloss: "to say, speak, tell, call, name", occurrences: 2354 },
  { strongs: "G1097", lemma: "γινώσκω", greek: "γινώσκω", transliteration: "ginṓskō", pronunciation: "ghin-OHS-ko", partOfSpeech: "Verb", gloss: "to know, perceive, learn, understand, acknowledge", occurrences: 223 },
  { strongs: "G4100", lemma: "πιστεύω", greek: "πιστεύω", transliteration: "pisteúō", pronunciation: "pis-TYOO-oh", partOfSpeech: "Verb", gloss: "to believe, trust, have faith in, commit", occurrences: 248 },
  { strongs: "G4102", lemma: "πίστις", greek: "πίστις", transliteration: "pístis", pronunciation: "PIS-tis", partOfSpeech: "Noun", gloss: "faith, trust, belief, confidence, conviction", occurrences: 244 },
  { strongs: "G26", lemma: "ἀγάπη", greek: "ἀγάπη", transliteration: "agápē", pronunciation: "a-GAH-pay", partOfSpeech: "Noun", gloss: "love, affection, good will, benevolence", occurrences: 116 },
  { strongs: "G25", lemma: "ἀγαπάω", greek: "ἀγαπάω", transliteration: "agapáō", pronunciation: "a-ga-PAH-oh", partOfSpeech: "Verb", gloss: "to love, dearly, cherish, have affection for", occurrences: 143 },
  { strongs: "G4991", lemma: "σωτηρία", greek: "σωτηρία", transliteration: "sōtēría", pronunciation: "so-tay-REE-ah", partOfSpeech: "Noun", gloss: "salvation, deliverance, preservation, safety", occurrences: 46 },
  { strongs: "G4990", lemma: "σωτήρ", greek: "σωτήρ", transliteration: "sōtḗr", pronunciation: "so-TARE", partOfSpeech: "Noun", gloss: "savior, deliverer, preserver", occurrences: 24 },
  { strongs: "G5547", lemma: "Χριστός", greek: "Χριστός", transliteration: "Christós", pronunciation: "khris-TOS", partOfSpeech: "Noun", gloss: "Christ, Messiah, anointed one", occurrences: 531 },
  { strongs: "G2424", lemma: "Ἰησοῦς", greek: "Ἰησοῦς", transliteration: "Iēsoûs", pronunciation: "ee-ay-SOOS", partOfSpeech: "Noun", gloss: "Jesus, Joshua, the Lord Jesus Christ", occurrences: 917 },
  { strongs: "G2962", lemma: "κύριος", greek: "κύριος", transliteration: "kýrios", pronunciation: "KYOO-ree-os", partOfSpeech: "Noun", gloss: "Lord, master, owner, sir, sovereign", occurrences: 718 },
  { strongs: "G4151", lemma: "πνεῦμα", greek: "πνεῦμα", transliteration: "pneûma", pronunciation: "PNYOO-mah", partOfSpeech: "Noun", gloss: "Spirit, breath, wind, ghost, spiritual being", occurrences: 379 },
  { strongs: "G3772", lemma: "οὐρανός", greek: "οὐρανός", transliteration: "ouranós", pronunciation: "oo-ra-NOS", partOfSpeech: "Noun", gloss: "heaven, sky, air, celestial realm", occurrences: 273 },
  { strongs: "G1093", lemma: "γῆ", greek: "γῆ", transliteration: "gē", pronunciation: "gay", partOfSpeech: "Noun", gloss: "earth, land, ground, world, soil, country", occurrences: 252 },
  { strongs: "G228", lemma: "ἀληθινός", greek: "ἀληθινός", transliteration: "alēthinós", pronunciation: "a-lay-thee-NOS", partOfSpeech: "Adjective", gloss: "true, genuine, real, faithful, truthful", occurrences: 28 },
  { strongs: "G225", lemma: "ἀλήθεια", greek: "ἀλήθεια", transliteration: "alḗtheia", pronunciation: "a-LAY-thay-ah", partOfSpeech: "Noun", gloss: "truth, reality, truthfulness, faithfullness", occurrences: 109 },
  { strongs: "G5485", lemma: "χάρις", greek: "χάρις", transliteration: "cháris", pronunciation: "KHA-ris", partOfSpeech: "Noun", gloss: "grace, favor, thankfulness, kindness, blessing", occurrences: 155 },
  { strongs: "G165", lemma: "αἰών", greek: "αἰών", transliteration: "aiṓn", pronunciation: "ahee-OHN", partOfSpeech: "Noun", gloss: "age, eternity, world, forever, everlasting", occurrences: 122 },
  { strongs: "G2222", lemma: "ζωή", greek: "ζωή", transliteration: "zōḗ", pronunciation: "zo-AY", partOfSpeech: "Noun", gloss: "life, living, existence, vitality, salvation-life", occurrences: 135 },
  { strongs: "G5457", lemma: "φῶς", greek: "φῶς", transliteration: "phōs", pronunciation: "foce", partOfSpeech: "Noun", gloss: "light, illumination, brightness, truth, knowledge", occurrences: 73 },
  { strongs: "G2889", lemma: "κόσμος", greek: "κόσμος", transliteration: "kósmos", pronunciation: "KOS-mos", partOfSpeech: "Noun", gloss: "world, universe, earth, mankind, adornment", occurrences: 186 },
  { strongs: "G4561", lemma: "σάρξ", greek: "σάρξ", transliteration: "sárx", pronunciation: "sarx", partOfSpeech: "Noun", gloss: "flesh, body, physical nature, humanity", occurrences: 147 },
  { strongs: "G129", lemma: "αἷμα", greek: "αἷμα", transliteration: "haîma", pronunciation: "HAY-mah", partOfSpeech: "Noun", gloss: "blood, bloodshed, lineage, lifeblood", occurrences: 99 },
  { strongs: "G1242", lemma: "διαθήκη", greek: "διαθήκη", transliteration: "diathḗkē", pronunciation: "dee-a-THAY-kay", partOfSpeech: "Noun", gloss: "covenant, testament, will, compact", occurrences: 33 },
  { strongs: "G932", lemma: "βασιλεία", greek: "βασιλεία", transliteration: "basileía", pronunciation: "ba-si-LAY-ah", partOfSpeech: "Noun", gloss: "kingdom, reign, sovereignty, royal power", occurrences: 162 },
  { strongs: "G1411", lemma: "δύναμις", greek: "δύναμις", transliteration: "dýnamis", pronunciation: "DOO-na-mis", partOfSpeech: "Noun", gloss: "power, might, strength, ability, miracle, force", occurrences: 119 },
  { strongs: "G1391", lemma: "δόξα", greek: "δόξα", transliteration: "dóxa", pronunciation: "DOX-ah", partOfSpeech: "Noun", gloss: "glory, honor, praise, splendor, brightness", occurrences: 166 },
  { strongs: "G4103", lemma: "πιστός", greek: "πιστός", transliteration: "pistós", pronunciation: "pis-TOS", partOfSpeech: "Adjective", gloss: "faithful, trustworthy, believing, reliable", occurrences: 67 },
  { strongs: "G264", lemma: "ἁμαρτάνω", greek: "ἁμαρτάνω", transliteration: "hamartánō", pronunciation: "ha-mar-TAH-no", partOfSpeech: "Verb", gloss: "to sin, transgress, err, miss the mark", occurrences: 43 },
  { strongs: "G266", lemma: "ἁμαρτία", greek: "ἁμαρτία", transliteration: "hamartía", pronunciation: "ha-mar-TEE-ah", partOfSpeech: "Noun", gloss: "sin, transgression, offense, sinful nature", occurrences: 173 },
  { strongs: "G3340", lemma: "μετανοέω", greek: "μετανοέω", transliteration: "metanoéō", pronunciation: "meh-ta-no-EH-oh", partOfSpeech: "Verb", gloss: "to repent, reconsider, change one's mind, turn from sin", occurrences: 34 },
  { strongs: "G3341", lemma: "μετάνοια", greek: "μετάνοια", transliteration: "metánoia", pronunciation: "meh-TAH-no-yah", partOfSpeech: "Noun", gloss: "repentance, change of mind, conversion, turning from sin", occurrences: 22 },
  { strongs: "G36", lemma: "ἀγενής", greek: "ἀγενής", transliteration: "agenḗs", pronunciation: "a-ghen-ACE", partOfSpeech: "Adjective", gloss: "low-born, base, humble, insignificant", occurrences: 1 },
  { strongs: "G40", lemma: "ἅγιος", greek: "ἅγιος", transliteration: "hágios", pronunciation: "HAH-gee-os", partOfSpeech: "Adjective", gloss: "holy, saintly, consecrated, pure, sacred", occurrences: 233 },
  { strongs: "G37", lemma: "ἁγιάζω", greek: "ἁγιάζω", transliteration: "hagiázō", pronunciation: "hah-gee-AH-zo", partOfSpeech: "Verb", gloss: "to sanctify, consecrate, make holy, purify", occurrences: 29 },
  { strongs: "G5207", lemma: "υἱός", greek: "υἱός", transliteration: "huiós", pronunciation: "hwee-OS", partOfSpeech: "Noun", gloss: "son, child, descendant, offspring, heir", occurrences: 382 },
  { strongs: "G5204", lemma: "ὕδωρ", greek: "ὕδωρ", transliteration: "hýdōr", pronunciation: "HYOO-dore", partOfSpeech: "Noun", gloss: "water, living water, rain, flood", occurrences: 76 },
  { strongs: "G5456", lemma: "φωνή", greek: "φωνή", transliteration: "phōnḗ", pronunciation: "fo-NAY", partOfSpeech: "Noun", gloss: "voice, sound, noise, language, call", occurrences: 139 },
  { strongs: "G991", lemma: "βλέπω", greek: "βλέπω", transliteration: "blépō", pronunciation: "BLEH-po", partOfSpeech: "Verb", gloss: "to see, look, behold, perceive, observe, consider", occurrences: 132 },
];

export const lexiconData = [...strongsHebrew, ...strongsGreek];
