export interface EntityData {
  name: string;
  slug: string;
  type: string;
  summary: string;
  background: string;
  dateRange?: string;
  occurrences: { reference: string; text: string }[];
  connections: { name: string; type: string; relationship: string }[];
  timeline: { date: string; label: string }[];
}

export const entityData: EntityData[] = [
  {
    name: 'Abraham',
    slug: 'abraham',
    type: 'Person',
    summary: 'Patriarch of the Israelite nation, called by God from Ur of the Chaldeans to found a covenant people.',
    background: 'Abraham (originally Abram) appears in Genesis 11-25 as the founding patriarch of Israel. His story begins in Ur of the Chaldeans (southern Mesopotamia), from which God called him to journey to Canaan. The Abrahamic covenant — land, descendants, and blessing to all nations — forms the theological backbone of the Hebrew Bible. Archaeological evidence from the Middle Bronze Age (c. 2000-1550 BC) shows nomadic pastoralists moving along the Fertile Crescent corridor, consistent with the patriarch narrative.',
    dateRange: 'c. 2000 BC',
    occurrences: [
      { reference: 'Genesis 12:1', text: 'Now the LORD said to Abram, "Go from your country..."' },
      { reference: 'Genesis 15:6', text: 'And he believed the LORD, and he counted it to him as righteousness.' },
      { reference: 'Genesis 17:5', text: 'No longer shall your name be called Abram, but your name shall be Abraham...' },
      { reference: 'Genesis 22:1-19', text: 'The binding of Isaac' },
    ],
    connections: [
      { name: 'Sarah', type: 'Person', relationship: 'Spouse' },
      { name: 'Isaac', type: 'Person', relationship: 'Son' },
      { name: 'Jacob', type: 'Person', relationship: 'Grandson' },
      { name: 'Canaan', type: 'Place', relationship: 'Destination' },
      { name: 'Covenant', type: 'Concept', relationship: 'Covenant recipient' },
    ],
    timeline: [
      { date: 'c. 2000 BC', label: 'Call of Abram' },
      { date: 'c. 2000 BC', label: 'Covenant established' },
      { date: 'c. 1990 BC', label: 'Birth of Ishmael' },
      { date: 'c. 1985 BC', label: 'Birth of Isaac' },
      { date: 'c. 1950 BC', label: 'Binding of Isaac' },
    ],
  },
  {
    name: 'Moses',
    slug: 'moses',
    type: 'Person',
    summary: 'Prophet, lawgiver, and leader who delivered Israel from Egyptian bondage and received the Torah at Sinai.',
    background: 'Moses is the central figure of the Pentateuch (Exodus-Deuteronomy). Born under Egyptian oppression, raised in Pharaoh\'s court, he fled to Midian after killing an Egyptian slavemaster. At the burning bush, God commissioned him to demand Israel\'s release. The Exodus from Egypt, the Sinai covenant, and the giving of the Law define his legacy. Moses is traditionally credited with authoring the Torah. Extra-biblical references include mentions in Greek (Hecataeus of Abdera) and Egyptian sources.',
    dateRange: 'c. 1520-1400 BC',
    occurrences: [
      { reference: 'Exodus 3:1-15', text: 'The burning bush' },
      { reference: 'Exodus 14:21-31', text: 'The crossing of the Red Sea' },
      { reference: 'Exodus 20:1-21', text: 'The Ten Commandments' },
      { reference: 'Deuteronomy 34:1-8', text: 'The death of Moses' },
    ],
    connections: [
      { name: 'Aaron', type: 'Person', relationship: 'Brother' },
      { name: 'Joshua', type: 'Person', relationship: 'Successor' },
      { name: 'Covenant', type: 'Concept', relationship: 'Mosaic covenant mediator' },
      { name: 'Egypt', type: 'Place', relationship: 'Oppressor' },
    ],
    timeline: [
      { date: 'c. 1520 BC', label: 'Birth of Moses' },
      { date: 'c. 1480 BC', label: 'Flight to Midian' },
      { date: 'c. 1446 BC', label: 'The Exodus' },
      { date: 'c. 1446 BC', label: 'Sinai covenant' },
      { date: 'c. 1406 BC', label: 'Death on Mount Nebo' },
    ],
  },
  {
    name: 'David',
    slug: 'david',
    type: 'Person',
    summary: 'Second king of Israel, founder of the Davidic dynasty, and central figure in the establishment of Jerusalem as the religious and political capital.',
    background: 'David rose from shepherd to become Israel\'s greatest king. His story is told in 1-2 Samuel and 1 Kings. He defeated Goliath, united the tribes, conquered Jerusalem, and brought the Ark of the Covenant there. God made a covenant with him promising an eternal dynasty (2 Samuel 7). The Tel Dan Stele (9th century BC) mentions the "House of David," providing the earliest extra-biblical evidence for the Davidic line.',
    dateRange: 'c. 1040-970 BC',
    occurrences: [
      { reference: '1 Samuel 17:1-58', text: 'David and Goliath' },
      { reference: '2 Samuel 5:1-12', text: 'David becomes king' },
      { reference: '2 Samuel 7:1-17', text: 'The Davidic covenant' },
      { reference: 'Psalm 23:1', text: 'The LORD is my shepherd; I shall not want.' },
    ],
    connections: [
      { name: 'Solomon', type: 'Person', relationship: 'Son' },
      { name: 'Jerusalem', type: 'Place', relationship: 'Capital city' },
      { name: 'Covenant', type: 'Concept', relationship: 'Davidic covenant recipient' },
      { name: 'Goliath', type: 'Person', relationship: 'Adversary' },
    ],
    timeline: [
      { date: 'c. 1040 BC', label: 'Birth of David' },
      { date: 'c. 1025 BC', label: 'Anointed by Samuel' },
      { date: 'c. 1010 BC', label: 'Becomes king of Judah' },
      { date: 'c. 1003 BC', label: 'Conquers Jerusalem' },
      { date: 'c. 970 BC', label: 'Death of David' },
    ],
  },
  {
    name: 'Solomon',
    slug: 'solomon',
    type: 'Person',
    summary: 'Son of David, third king of Israel, renowned for wisdom, wealth, and building the First Temple in Jerusalem.',
    background: 'Solomon inherited a united kingdom from David and expanded it through trade, diplomacy, and building projects. His construction of the Temple (c. 960 BC) established Jerusalem as the central sanctuary. He is credited with the Book of Proverbs, Ecclesiastes, and Song of Solomon. The united monarchy fractured after his reign due to heavy taxation and forced labor. Archaeological evidence includes the Stepped Stone Structure and the "House of the Forest of Lebanon" in Jerusalem.',
    dateRange: 'c. 990-931 BC',
    occurrences: [
      { reference: '1 Kings 3:1-15', text: 'Solomon asks for wisdom' },
      { reference: '1 Kings 6:1-38', text: 'Building of the Temple' },
      { reference: '1 Kings 10:1-13', text: 'The Queen of Sheba' },
    ],
    connections: [
      { name: 'David', type: 'Person', relationship: 'Father' },
      { name: 'Jerusalem', type: 'Place', relationship: 'City of the Temple' },
      { name: 'Egypt', type: 'Place', relationship: 'Trade partner' },
    ],
    timeline: [
      { date: 'c. 970 BC', label: 'Becomes king' },
      { date: 'c. 960 BC', label: 'Temple completed' },
      { date: 'c. 931 BC', label: 'Death of Solomon' },
    ],
  },
  {
    name: 'Isaiah',
    slug: 'isaiah',
    type: 'Person',
    summary: 'Major prophet in Jerusalem during the 8th century BC, whose book addresses judgment, hope, and the coming of the Messiah.',
    background: 'Isaiah prophesied during the reigns of Uzziah, Jotham, Ahaz, and Hezekiah of Judah (c. 740-700 BC). His book spans oracles of judgment against Israel and the nations, the call to trust God rather than foreign alliances, and visions of a future restored Jerusalem. The Great Isaiah Scroll (1QIsaa) found at Qumran dates to c. 125 BC and is one of the most important Dead Sea Scrolls.',
    dateRange: 'c. 740-680 BC',
    occurrences: [
      { reference: 'Isaiah 6:1-8', text: 'Isaiah\'s vision and call' },
      { reference: 'Isaiah 7:14', text: 'The virgin shall conceive' },
      { reference: 'Isaiah 40:1-5', text: 'Comfort for God\'s people' },
      { reference: 'Isaiah 53:1-12', text: 'The suffering servant' },
    ],
    connections: [
      { name: 'Jerusalem', type: 'Place', relationship: 'City of prophecy' },
      { name: 'Messiah', type: 'Concept', relationship: 'Prophecy' },
      { name: 'Hezekiah', type: 'Person', relationship: 'Contemporary' },
    ],
    timeline: [
      { date: 'c. 740 BC', label: 'Isaiah\'s call' },
      { date: 'c. 734 BC', label: 'Syro-Ephraimite crisis' },
      { date: 'c. 701 BC', label: 'Assyrian siege of Jerusalem' },
    ],
  },
  {
    name: 'Paul',
    slug: 'paul',
    type: 'Person',
    summary: 'Apostle to the Gentiles, theologian, and missionary whose letters form a major portion of the New Testament.',
    background: 'Paul (originally Saul of Tarsus) was a Pharisee who persecuted Christians before a dramatic conversion on the road to Damascus. He became the foremost missionary to the non-Jewish world, founding churches across Asia Minor and Greece. His 13 letters (the Pauline epistles) articulate core Christian theology — justification by faith, the role of the Law, the nature of the Church, and eschatological hope. He was martyred in Rome under Nero c. AD 64-67.',
    dateRange: 'c. AD 5-67',
    occurrences: [
      { reference: 'Acts 9:1-19', text: 'Conversion on the road to Damascus' },
      { reference: 'Romans 3:21-26', text: 'Righteousness through faith' },
      { reference: '1 Corinthians 13:1-13', text: 'The love chapter' },
      { reference: 'Philippians 3:4-14', text: 'The surpassing worth of knowing Christ' },
    ],
    connections: [
      { name: 'Peter', type: 'Person', relationship: 'Fellow apostle' },
      { name: 'Timothy', type: 'Person', relationship: 'Mentee' },
      { name: 'Rome', type: 'Place', relationship: 'Imprisonment and martyrdom' },
    ],
    timeline: [
      { date: 'c. AD 5', label: 'Birth in Tarsus' },
      { date: 'c. AD 33-35', label: 'Conversion' },
      { date: 'c. AD 47-57', label: 'Missionary journeys' },
      { date: 'c. AD 57-59', label: 'Imprisonment in Caesarea' },
      { date: 'c. AD 60-62', label: 'House arrest in Rome' },
      { date: 'c. AD 64-67', label: 'Martyrdom' },
    ],
  },
  {
    name: 'Canaan',
    slug: 'canaan',
    type: 'Place',
    summary: 'The land promised to Abraham and his descendants, located between the Mediterranean Sea and the Jordan River.',
    background: 'Canaan refers to the region roughly corresponding to modern-day Israel, Palestine, Lebanon, and parts of Syria. In the Amarna Letters (14th century BC), Canaan is described as a collection of city-states under Egyptian hegemony. The Hebrew Bible presents Canaan as the land promised to Abraham, later conquered under Joshua. Archaeological evidence shows continuous settlement from the Chalcolithic period through the Bronze and Iron Ages.',
    dateRange: 'Bronze Age - Iron Age',
    occurrences: [
      { reference: 'Genesis 12:5', text: 'Abram took Sarai his wife... and they set out for the land of Canaan.' },
      { reference: 'Genesis 17:8', text: 'And I will give to you and to your offspring... all the land of Canaan.' },
    ],
    connections: [
      { name: 'Abraham', type: 'Person', relationship: 'Promised to' },
      { name: 'Egypt', type: 'Place', relationship: 'Neighbor' },
      { name: 'Jerusalem', type: 'Place', relationship: 'Principal city' },
    ],
    timeline: [
      { date: 'c. 2000 BC', label: 'Abraham arrives' },
      { date: 'c. 1400 BC', label: 'Conquest under Joshua' },
      { date: 'c. 1000 BC', label: 'United Monarchy' },
      { date: 'c. 722 BC', label: 'Northern kingdom falls' },
      { date: 'c. 586 BC', label: 'Southern kingdom falls' },
    ],
  },
  {
    name: 'Egypt',
    slug: 'egypt',
    type: 'Place',
    summary: 'Ancient civilization along the Nile, a major power in the biblical world and setting of the Exodus narrative.',
    background: 'Egypt was one of the great powers of the ancient Near East. Its frequent biblical appearances include Abraham\'s sojourn, Joseph\'s rise to power, the oppression of the Israelites, the Exodus, and as a political ally or adversary during the monarchy. Egyptian records mention Israel (Merneptah Stele, c. 1208 BC) and provide crucial context for dating biblical events.',
    dateRange: 'c. 3100 BC - present',
    occurrences: [
      { reference: 'Exodus 1:8-14', text: 'A new king arose over Egypt who did not know Joseph.' },
      { reference: 'Exodus 12:31-42', text: 'The Exodus from Egypt' },
      { reference: '1 Kings 3:1', text: 'Solomon made a marriage alliance with Egypt.' },
    ],
    connections: [
      { name: 'Moses', type: 'Person', relationship: 'Raised in Pharaoh\'s court' },
      { name: 'Joseph', type: 'Person', relationship: 'Rose to power in Egypt' },
      { name: 'Canaan', type: 'Place', relationship: 'Neighbor' },
    ],
    timeline: [
      { date: 'c. 2000 BC', label: 'Abraham visits Egypt' },
      { date: 'c. 1876 BC', label: 'Joseph in Egypt' },
      { date: 'c. 1446 BC', label: 'The Exodus' },
      { date: 'c. 925 BC', label: 'Shishak invades Judah' },
      { date: 'c. 701 BC', label: 'Tirhakah vs. Assyria' },
    ],
  },
  {
    name: 'Jerusalem',
    slug: 'jerusalem',
    type: 'Place',
    summary: 'Capital of the united monarchy under David and site of the Temple, the religious and political center of ancient Israel.',
    background: 'Jerusalem has been continuously inhabited since the Chalcolithic period (c. 3000 BC). David conquered the Jebusite city and made it his capital. Solomon built the First Temple there. The city was destroyed by Babylon in 586 BC, rebuilt after the exile, and expanded under Herod the Great. The City of David excavations, Hezekiah\'s Tunnel, and the Temple Mount remain key archaeological sites.',
    dateRange: 'c. 3000 BC - present',
    occurrences: [
      { reference: '2 Samuel 5:6-10', text: 'David captures Jerusalem' },
      { reference: '1 Kings 8:1-13', text: 'Dedication of the Temple' },
      { reference: 'Psalm 122:1-9', text: 'Prayer for the peace of Jerusalem' },
      { reference: 'Isaiah 2:1-5', text: 'The mountain of the LORD\'s house' },
    ],
    connections: [
      { name: 'David', type: 'Person', relationship: 'Captured and established as capital' },
      { name: 'Solomon', type: 'Person', relationship: 'Built the Temple' },
      { name: 'Canaan', type: 'Place', relationship: 'Principal city of' },
    ],
    timeline: [
      { date: 'c. 1003 BC', label: 'David conquers Jerusalem' },
      { date: 'c. 960 BC', label: 'Temple completed' },
      { date: 'c. 586 BC', label: 'Destroyed by Babylon' },
      { date: 'c. 515 BC', label: 'Second Temple completed' },
      { date: 'c. 20 BC', label: 'Herod\'s Temple expansion' },
      { date: 'AD 70', label: 'Destroyed by Rome' },
    ],
  },
  {
    name: 'Babylon',
    slug: 'babylon',
    type: 'Place',
    summary: 'Ancient Mesopotamian empire that conquered Judah, destroyed Jerusalem, and exiled the Judean population (586 BC).',
    background: 'Babylon rose to prominence under Hammurabi (c. 1792 BC) and later under the Neo-Babylonian empire (626-539 BC). Nebuchadnezzar II conquered Jerusalem in 597 and 586 BC, destroying the Temple and exiling much of the population. Babylon features prominently in prophetic literature as both a historical empire and a symbol of human pride and divine judgment. The Ishtar Gate and Hanging Gardens were among its wonders.',
    dateRange: 'c. 1894-539 BC',
    occurrences: [
      { reference: '2 Kings 25:1-21', text: 'Fall of Jerusalem to Babylon' },
      { reference: 'Psalm 137:1-4', text: 'By the waters of Babylon' },
      { reference: 'Daniel 1:1-7', text: 'Daniel in Babylon' },
    ],
    connections: [
      { name: 'Jerusalem', type: 'Place', relationship: 'Conquered' },
      { name: 'Daniel', type: 'Person', relationship: 'Exile in Babylon' },
      { name: 'Covenant', type: 'Concept', relationship: 'Exile as covenant judgment' },
    ],
    timeline: [
      { date: 'c. 605 BC', label: 'First deportation' },
      { date: 'c. 597 BC', label: 'Second deportation' },
      { date: 'c. 586 BC', label: 'Destruction of Jerusalem' },
      { date: 'c. 539 BC', label: 'Fall of Babylon to Persia' },
    ],
  },
  {
    name: 'Covenant',
    slug: 'covenant',
    type: 'Concept',
    summary: 'A binding agreement between God and humanity, central to biblical theology.',
    background: 'The Hebrew term berit appears over 280 times in the Old Testament. Ancient Near Eastern covenants followed the suzerain-vassal treaty pattern: preamble, historical prologue, stipulations, witnesses, blessings and curses. The Abrahamic covenant (Genesis 15, 17) is unconditional — God alone passes through the severed animals. The Mosaic covenant (Exodus 19-24) is conditional, requiring Israel\'s obedience. The Davidic covenant (2 Samuel 7) promises an eternal dynasty. Jeremiah 31 prophesies a new covenant written on the heart.',
    occurrences: [
      { reference: 'Genesis 15:18', text: 'On that day the LORD made a covenant with Abram...' },
      { reference: 'Exodus 24:8', text: 'Behold the blood of the covenant...' },
      { reference: '2 Samuel 7:12-16', text: 'The Davidic covenant' },
      { reference: 'Jeremiah 31:31-34', text: 'A new covenant written on the heart' },
    ],
    connections: [
      { name: 'Abraham', type: 'Person', relationship: 'Covenant recipient' },
      { name: 'Moses', type: 'Person', relationship: 'Mosaic covenant mediator' },
      { name: 'David', type: 'Person', relationship: 'Davidic covenant recipient' },
    ],
    timeline: [
      { date: 'c. 2000 BC', label: 'Abrahamic covenant' },
      { date: 'c. 1446 BC', label: 'Mosaic covenant' },
      { date: 'c. 1000 BC', label: 'Davidic covenant' },
      { date: 'c. 600 BC', label: 'New covenant prophesied by Jeremiah' },
    ],
  },
  {
    name: 'Exile',
    slug: 'exile',
    type: 'Concept',
    summary: 'The forced displacement of the Israelite and Judean populations by Assyria (722 BC) and Babylon (586 BC), a defining event in biblical history.',
    background: 'The Assyrian exile of the northern kingdom (Israel) in 722 BC scattered the ten tribes. The Babylonian exile of the southern kingdom (Judah) in 586 BC lasted approximately 70 years until Cyrus of Persia allowed return in 539 BC. The exile transformed Israelite religion — the rise of synagogues, the centrality of the Torah, the development of apocalyptic thought, and the shift from prophecy to wisdom literature all trace to this period.',
    occurrences: [
      { reference: '2 Kings 17:1-23', text: 'The fall of Samaria and Assyrian exile' },
      { reference: 'Psalm 137:1-6', text: 'By the waters of Babylon, we wept' },
      { reference: 'Ezra 1:1-4', text: 'Cyrus decrees the return' },
    ],
    connections: [
      { name: 'Babylon', type: 'Place', relationship: 'Place of exile' },
      { name: 'Jerusalem', type: 'Place', relationship: 'Lost and restored' },
      { name: 'Covenant', type: 'Concept', relationship: 'Exile as covenant curse' },
    ],
    timeline: [
      { date: 'c. 722 BC', label: 'Assyrian exile of Israel' },
      { date: 'c. 597 BC', label: 'First Babylonian deportation' },
      { date: 'c. 586 BC', label: 'Destruction of Jerusalem' },
      { date: 'c. 539 BC', label: 'Cyrus decrees return' },
      { date: 'c. 516 BC', label: 'Temple rebuilt' },
    ],
  },
  {
    name: 'Divine Council',
    slug: 'divine-council',
    type: 'Concept',
    summary: 'The assembly of divine beings (bene elohim) surrounding Yahweh in the heavenly court, reflecting ANE conceptions of divine monarchy.',
    background: 'The Divine Council is a recurring motif throughout the Hebrew Bible and ancient Near Eastern literature. In Canaanite religion, El presided over a council of 70 gods (the bene elim). Biblical monotheism subverts this: Yahweh presides over a council of divine beings (Psalm 82, Job 1-2, 1 Kings 22:19-23) who are his attendants, not competitors. These beings are called "sons of God" (bene elohim), "holy ones" (qedoshim), or "host of heaven" (seba hashamayim). Deuteronomy 32:8-9 (in the Dead Sea Scrolls and Septuagint) suggests Yahweh inherited Israel as his portion when the Most High (Elyon) divided the nations among the gods. The council structure directly informs biblical angelology, the development of the Son of Man figure in Daniel 7, and later Jewish and Christian concepts of the heavenly host.',
    occurrences: [
      { reference: 'Psalm 82:1', text: 'God has taken his place in the divine council...' },
      { reference: 'Job 1:6', text: 'Now there was a day when the sons of God came to present themselves before the LORD...' },
      { reference: '1 Kings 22:19', text: 'I saw the LORD sitting on his throne, and all the host of heaven standing beside him...' },
      { reference: 'Deuteronomy 32:8', text: 'When the Most High gave to the nations their inheritance...' },
      { reference: 'Daniel 7:9-10', text: 'The Ancient of Days took his seat... ten thousand times ten thousand stood before him.' },
    ],
    connections: [
      { name: 'Isaiah', type: 'Person', relationship: 'Vision of the council' },
      { name: 'Jerusalem', type: 'Place', relationship: 'Earthly counterpart: the Temple' },
      { name: 'Covenant', type: 'Concept', relationship: 'Council members as covenant witnesses' },
    ],
    timeline: [
      { date: 'c. 1400 BC', label: 'Deuteronomy 32:8 (traditional date)' },
      { date: 'c. 875 BC', label: '1 Kings 22 — Micaiah\'s vision' },
      { date: 'c. 750 BC', label: 'Isaiah 6 — Isaiah\'s vision' },
      { date: 'c. 500 BC', label: 'Psalm 82 — God judges the gods' },
      { date: 'c. 165 BC', label: 'Daniel 7 — Son of Man' },
    ],
  },
  {
    name: 'Wisdom',
    slug: 'wisdom',
    type: 'Concept',
    summary: 'A theological and literary tradition in ancient Israel emphasizing practical skill in living, fear of the Lord, and the order of creation.',
    background: 'Biblical wisdom literature (Proverbs, Job, Ecclesiastes, some Psalms) reflects an international tradition found across the ancient Near East, including Egyptian (Instruction of Amenemope), Mesopotamian (I Will Praise the Lord of Wisdom), and Canaanite sources. Hebrew wisdom (hokhmah) begins with the "fear of the LORD" (Proverbs 1:7) and sees creation as an ordered system established by God. Wisdom is personified as a woman in Proverbs 8-9, a figure that later influences both the Logos theology of John\'s Gospel and Gnostic speculations. The wisdom tradition is skeptical of simple retribution theology (Job), explores the meaning of life under the sun (Ecclesiastes), and offers practical guidance for daily living (Proverbs).',
    occurrences: [
      { reference: 'Proverbs 1:7', text: 'The fear of the LORD is the beginning of knowledge...' },
      { reference: 'Proverbs 8:22-31', text: 'The LORD possessed me at the beginning of his work...' },
      { reference: 'Job 28:12-28', text: 'Where shall wisdom be found?' },
      { reference: 'Ecclesiastes 1:1-11', text: 'Vanity of vanities, all is vanity.' },
    ],
    connections: [
      { name: 'Solomon', type: 'Person', relationship: 'Patron of wisdom tradition' },
      { name: 'Divine Council', type: 'Concept', relationship: 'Wisdom as creational order' },
    ],
    timeline: [
      { date: 'c. 950 BC', label: 'Solomon — early proverbs' },
      { date: 'c. 700 BC', label: 'Hezekiah\'s collection of Proverbs' },
      { date: 'c. 600 BC', label: 'Job composed' },
      { date: 'c. 400 BC', label: 'Ecclesiastes' },
      { date: 'c. 180 BC', label: 'Wisdom of Ben Sira' },
    ],
  },
  {
    name: 'Atonement',
    slug: 'atonement',
    type: 'Concept',
    summary: 'The biblical concept of covering or purging sin through sacrificial ritual, culminating in the Day of Atonement (Yom Kippur).',
    background: 'The Hebrew root kaphar (כָּפַר) means "to cover, appease, make atonement." In the Priestly tradition (P), atonement is accomplished through blood manipulation in the sanctuary ritual. On Yom Kippur (Leviticus 16), the high priest enters the Holy of Holies to purge the sanctuary of accumulated impurity, and the scapegoat (Azazel) carries Israel\'s sins into the wilderness. The blood of the sacrifice does not "pay" God but purges the sanctuary of the pollution caused by sin. This priestly theology was reinterpreted in the New Testament (especially Hebrews) to frame Jesus\'s death as the definitive atonement — the ultimate sacrifice entering the heavenly sanctuary.',
    occurrences: [
      { reference: 'Leviticus 16:1-34', text: 'The Day of Atonement ritual' },
      { reference: 'Leviticus 17:11', text: 'The life of the flesh is in the blood, and I have given it for you on the altar to make atonement...' },
      { reference: 'Hebrews 9:1-28', text: 'Christ entered the holy places made without hands...' },
      { reference: 'Romans 3:25', text: 'God put forward [Christ] as a propitiation by his blood...' },
    ],
    connections: [
      { name: 'Covenant', type: 'Concept', relationship: 'Covenant maintenance ritual' },
      { name: 'Jerusalem', type: 'Place', relationship: 'Temple site of Yom Kippur' },
      { name: 'Exile', type: 'Concept', relationship: 'Loss of Temple and atonement' },
    ],
    timeline: [
      { date: 'c. 1440 BC', label: 'Leviticus 16 — Yom Kippur instituted' },
      { date: 'c. 960 BC', label: 'Temple — central sanctuary' },
      { date: 'c. 586 BC', label: 'Temple destroyed — atonement crisis' },
      { date: 'c. 515 BC', label: 'Second Temple — Yom Kippur restored' },
      { date: 'AD 70', label: 'Temple destroyed — post-sacrificial Judaism' },
    ],
  },
  {
    name: 'Messiah',
    slug: 'messiah',
    type: 'Concept',
    summary: 'The "anointed one" — originally referring to Israelite kings, later developing into an eschatological figure who would restore Israel.',
    background: 'The Hebrew mashiach means "anointed one" and originally applied to kings (Saul, David) and high priests who were anointed with oil as a sign of divine appointment. After the monarchy ended, the term developed eschatological connotations — a future Davidic king who would restore Israel\'s fortunes, defeat its enemies, and establish God\'s kingdom. The Dead Sea Scrolls show a diverse messianic expectation: a Royal Messiah (of David) and a Priestly Messiah (of Aaron), or in some texts, a single transcendent figure. The New Testament presents Jesus as this Messiah (Christos), reinterpreting messianic expectations around suffering (Isaiah 53) rather than military conquest.',
    occurrences: [
      { reference: 'Psalm 2:1-12', text: 'Why do the nations rage... against the LORD and against his Anointed?' },
      { reference: 'Daniel 9:25-26', text: 'From the going out of the word to restore and build Jerusalem to the coming of an Anointed One...' },
      { reference: 'Isaiah 61:1-3', text: 'The Spirit of the Lord GOD is upon me, because the LORD has anointed me...' },
    ],
    connections: [
      { name: 'David', type: 'Person', relationship: 'Archetype of the anointed king' },
      { name: 'Isaiah', type: 'Person', relationship: 'Messianic prophecies' },
      { name: 'Jerusalem', type: 'Place', relationship: 'Messianic reign' },
    ],
    timeline: [
      { date: 'c. 1000 BC', label: 'David — model of the anointed king' },
      { date: 'c. 586 BC', label: 'End of monarchy — messianic hope emerges' },
      { date: 'c. 200 BC', label: 'Diverse messianic expectations' },
      { date: 'c. 100 BC', label: 'Dead Sea Scrolls — dual messiahs' },
      { date: 'c. AD 30', label: 'Jesus as Messiah' },
    ],
  },
];
