export interface BibleChapter {
  book: string;
  chapter: number;
  translation: string;
  verses: { num: number; text: string; words?: { position: number; hebrew?: string; greek?: string; strongs?: string }[] }[];
  metadata?: { section: string; genre: string; dateRange: string };
}

const strongsGenesis1: { position: number; hebrew: string; greek?: string; strongs: string }[][] = [
  [{ position: 0, hebrew: 'בְּרֵאשִׁית', strongs: 'H7225' }, { position: 1, hebrew: 'בָּרָא', strongs: 'H1254' }, { position: 2, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 4, hebrew: 'שָׁמַיִם', strongs: 'H8064' }, { position: 5, hebrew: 'אֶרֶץ', strongs: 'H776' }],
  [{ position: 1, hebrew: 'הָיָה', strongs: 'H1961' }, { position: 2, hebrew: 'תֹּהוּ', strongs: 'H8414' }, { position: 4, hebrew: 'בֹּהוּ', strongs: 'H922' }, { position: 5, hebrew: 'חֹשֶׁךְ', strongs: 'H2822' }, { position: 8, hebrew: 'תְּהוֹם', strongs: 'H8415' }, { position: 11, hebrew: 'רוּחַ', strongs: 'H7307' }, { position: 12, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 14, hebrew: 'רָחַף', strongs: 'H7363' }],
  [{ position: 0, hebrew: 'אָמַר', strongs: 'H559' }, { position: 1, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 3, hebrew: 'אוֹר', strongs: 'H216' }, { position: 4, hebrew: 'הָיָה', strongs: 'H1961' }],
  [{ position: 0, hebrew: 'רָאָה', strongs: 'H7200' }, { position: 1, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 3, hebrew: 'אוֹר', strongs: 'H216' }, { position: 5, hebrew: 'טוֹב', strongs: 'H2896' }, { position: 7, hebrew: 'בָּדַל', strongs: 'H914' }, { position: 7, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 9, hebrew: 'אוֹר', strongs: 'H216' }],
  [{ position: 0, hebrew: 'קָרָא', strongs: 'H7121' }, { position: 1, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 3, hebrew: 'אוֹר', strongs: 'H216' }, { position: 5, hebrew: 'יוֹם', strongs: 'H3117' }, { position: 8, hebrew: 'קָרָא', strongs: 'H7121' }, { position: 10, hebrew: 'לַיְלָה', strongs: 'H3915' }, { position: 13, hebrew: 'עֶרֶב', strongs: 'H6153' }, { position: 15, hebrew: 'בֹּקֶר', strongs: 'H1242' }],
  [{ position: 0, hebrew: 'אָמַר', strongs: 'H559' }, { position: 1, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 4, hebrew: 'רָקִיעַ', strongs: 'H7549' }, { position: 8, hebrew: 'בָּדַל', strongs: 'H914' }, { position: 9, hebrew: 'מַיִם', strongs: 'H4325' }],
  [{ position: 0, hebrew: 'עָשָׂה', strongs: 'H6213' }, { position: 1, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 3, hebrew: 'רָקִיעַ', strongs: 'H7549' }, { position: 6, hebrew: 'בָּדַל', strongs: 'H914' }, { position: 9, hebrew: 'מַיִם', strongs: 'H4325' }],
  [{ position: 0, hebrew: 'קָרָא', strongs: 'H7121' }, { position: 1, hebrew: 'אֱלֹהִים', strongs: 'H430' }, { position: 3, hebrew: 'רָקִיעַ', strongs: 'H7549' }],
];

export const bibleChapters: BibleChapter[] = [
  // ===== WEB (World English Bible) =====
  {
    book: 'genesis', chapter: 1, translation: 'web',
    verses: [
      { num: 1, text: 'In the beginning, God created the heavens and the earth.', words: [...strongsGenesis1[0]] },
      { num: 2, text: 'The earth was formless and empty. Darkness was on the surface of the deep and God\'s Spirit was hovering over the surface of the waters.', words: [...strongsGenesis1[1]] },
      { num: 3, text: 'God said, "Let there be light," and there was light.', words: [...strongsGenesis1[2]] },
      { num: 4, text: 'God saw the light, and saw that it was good. God divided the light from the darkness.', words: [...strongsGenesis1[3]] },
      { num: 5, text: 'God called the light "day," and the darkness he called "night." There was evening and there was morning, the first day.', words: [...strongsGenesis1[4]] },
      { num: 6, text: 'God said, "Let there be an expanse in the middle of the waters, and let it divide the waters from the waters."', words: [...strongsGenesis1[5]] },
      { num: 7, text: 'God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so.', words: [...strongsGenesis1[6]] },
      { num: 8, text: 'God called the expanse "sky." There was evening and there was morning, the second day.', words: [...strongsGenesis1[7]] },
      { num: 9, text: 'God said, "Let the waters under the sky be gathered together to one place, and let the dry land appear;" and it was so.', words: [] },
      { num: 10, text: 'God called the dry land "earth," and the gathering together of the waters he called "seas." God saw that it was good.', words: [] },
      { num: 11, text: 'God said, "Let the earth yield grass, herbs yielding seeds, and fruit trees bearing fruit after their kind, with their seeds in it, on the earth;" and it was so.', words: [] },
      { num: 12, text: 'The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seeds in it, after their kind; and God saw that it was good.', words: [] },
      { num: 13, text: 'There was evening and there was morning, the third day.', words: [] },
      { num: 14, text: 'God said, "Let there be lights in the expanse of the sky to divide the day from the night; and let them be for signs to mark seasons, days, and years;"', words: [] },
      { num: 15, text: 'and let them be for lights in the expanse of the sky to give light on the earth;" and it was so.', words: [] },
      { num: 16, text: 'God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars.', words: [] },
      { num: 17, text: 'God set them in the expanse of the sky to give light to the earth,', words: [] },
      { num: 18, text: 'and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good.', words: [] },
      { num: 19, text: 'There was evening and there was morning, the fourth day.', words: [] },
      { num: 20, text: 'God said, "Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of the sky."', words: [] },
      { num: 21, text: 'God created the large sea creatures and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good.', words: [] },
      { num: 22, text: 'God blessed them, saying, "Be fruitful, multiply, and fill the waters in the seas, and let birds multiply on the earth."', words: [] },
      { num: 23, text: 'There was evening and there was morning, the fifth day.', words: [] },
      { num: 24, text: 'God said, "Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind;" and it was so.', words: [] },
      { num: 25, text: 'God made the animals of the earth after their kind, and the livestock after their kind, and every creeping thing of the ground after its kind. God saw that it was good.', words: [] },
      { num: 26, text: 'God said, "Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth."', words: [] },
      { num: 27, text: 'God created man in his own image. In God\'s image he created him; male and female he created them.', words: [] },
      { num: 28, text: 'God blessed them. God said to them, "Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth."', words: [] },
      { num: 29, text: 'God said, "Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food."', words: [] },
      { num: 30, text: 'To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;" and it was so.', words: [] },
      { num: 31, text: 'God saw everything that he had made, and indeed, it was very good. There was evening and there was morning, the sixth day.', words: [] },
    ],
    metadata: { section: 'Pentateuch', genre: 'Narrative', dateRange: '~1440-1400 BC' },
  },
  // ===== KJV (King James Version) =====
  {
    book: 'genesis', chapter: 1, translation: 'kjv',
    verses: [
      { num: 1, text: 'In the beginning God created the heaven and the earth.' },
      { num: 2, text: 'And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.' },
      { num: 3, text: 'And God said, Let there be light: and there was light.' },
      { num: 4, text: 'And God saw the light, that it was good: and God divided the light from the darkness.' },
      { num: 5, text: 'And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.' },
      { num: 6, text: 'And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.' },
      { num: 7, text: 'And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.' },
      { num: 8, text: 'And God called the firmament Heaven. And the evening and the morning were the second day.' },
      { num: 9, text: 'And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.' },
      { num: 10, text: 'And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.' },
      { num: 11, text: 'And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.' },
      { num: 12, text: 'And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.' },
      { num: 13, text: 'And the evening and the morning were the third day.' },
      { num: 14, text: 'And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:' },
      { num: 15, text: 'And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.' },
      { num: 16, text: 'And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.' },
      { num: 17, text: 'And God set them in the firmament of the heaven to give light upon the earth,' },
      { num: 18, text: 'And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.' },
      { num: 19, text: 'And the evening and the morning were the fourth day.' },
      { num: 20, text: 'And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.' },
      { num: 21, text: 'And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind, and every winged fowl after his kind: and God saw that it was good.' },
      { num: 22, text: 'And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth.' },
      { num: 23, text: 'And the evening and the morning were the fifth day.' },
      { num: 24, text: 'And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so.' },
      { num: 25, text: 'And God made the beast of the earth after his kind, and cattle after their kind, and every thing that creepeth upon the earth after his kind: and God saw that it was good.' },
      { num: 26, text: 'And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.' },
      { num: 27, text: 'So God created man in his own image, in the image of God created he him; male and female created he them.' },
      { num: 28, text: 'And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth.' },
      { num: 29, text: 'And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat.' },
      { num: 30, text: 'And to every beast of the earth, and to every fowl of the air, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for meat: and it was so.' },
      { num: 31, text: 'And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day.' },
    ],
    metadata: { section: 'Pentateuch', genre: 'Narrative', dateRange: '~1440-1400 BC' },
  },
  // ===== ASV (American Standard Version) =====
  {
    book: 'genesis', chapter: 1, translation: 'asv',
    verses: [
      { num: 1, text: 'In the beginning God created the heavens and the earth.' },
      { num: 2, text: 'And the earth was waste and void; and darkness was upon the face of the deep: and the Spirit of God moved upon the face of the waters.' },
      { num: 3, text: 'And God said, Let there be light: and there was light.' },
      { num: 4, text: 'And God saw the light, that it was good: and God divided the light from the darkness.' },
      { num: 5, text: 'And God called the light Day, and the darkness he called Night. And there was evening and there was morning, one day.' },
      { num: 6, text: 'And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.' },
      { num: 7, text: 'And God made the firmament, and divided the waters that were under the firmament from the waters that were above the firmament: and it was so.' },
      { num: 8, text: 'And God called the firmament Heaven. And there was evening and there was morning, a second day.' },
      { num: 9, text: 'And God said, Let the waters under the heavens be gathered together unto one place, and let the dry land appear: and it was so.' },
      { num: 10, text: 'And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.' },
      { num: 11, text: 'And God said, Let the earth put forth grass, herbs yielding seed, and fruit-trees bearing fruit after their kind, wherein is the seed thereof, upon the earth: and it was so.' },
      { num: 12, text: 'And the earth brought forth grass, herbs yielding seed after their kind, and trees bearing fruit, wherein is the seed thereof, after their kind: and God saw that it was good.' },
      { num: 13, text: 'And there was evening and there was morning, a third day.' },
      { num: 14, text: 'And God said, Let there be lights in the firmament of heaven to divide the day from the night; and let them be for signs, and for seasons, and for days and years:' },
      { num: 15, text: 'and let them be for lights in the firmament of heaven to give light upon the earth: and it was so.' },
      { num: 16, text: 'And God made the two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.' },
      { num: 17, text: 'And God set them in the firmament of heaven to give light upon the earth,' },
      { num: 18, text: 'and to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.' },
      { num: 19, text: 'And there was evening and there was morning, a fourth day.' },
      { num: 20, text: 'And God said, Let the waters swarm with swarms of living creatures, and let birds fly above the earth in the open firmament of heaven.' },
      { num: 21, text: 'And God created the great sea-monsters, and every living creature that moveth, wherewith the waters swarmed, after their kind, and every winged bird after its kind: and God saw that it was good.' },
      { num: 22, text: 'And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth.' },
      { num: 23, text: 'And there was evening and there was morning, a fifth day.' },
      { num: 24, text: 'And God said, Let the earth bring forth living creatures after their kind, cattle, and creeping things, and beasts of the earth after their kind: and it was so.' },
      { num: 25, text: 'And God made the beasts of the earth after their kind, and the cattle after their kind, and every creeping thing of the ground after its kind: and God saw that it was good.' },
      { num: 26, text: 'And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the heavens, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.' },
      { num: 27, text: 'And God created man in his own image, in the image of God created he him; male and female created he them.' },
      { num: 28, text: 'And God blessed them: and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it; and have dominion over the fish of the sea, and over the birds of the heavens, and over every living thing that moveth upon the earth.' },
      { num: 29, text: 'And God said, Behold, I have given you every herb yielding seed, which is upon the face of all the earth, and every tree, in which is the fruit of a tree yielding seed; to you it shall be for food:' },
      { num: 30, text: 'and to every beast of the earth, and to every bird of the heavens, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for food: and it was so.' },
      { num: 31, text: 'And God saw everything that he had made, and, behold, it was very good. And there was evening and there was morning, the sixth day.' },
    ],
    metadata: { section: 'Pentateuch', genre: 'Narrative', dateRange: '~1440-1400 BC' },
  },
];
